enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Custom header for YouTube' 'Visual preferences icons'"
excluded-patches = "'Enable debugging'"

[Spotify]
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
arch = "arm64-v8a"

[GooglePhotos]
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
build-mode = "apk"
apkmirror-dpi = "120-640dpi"

[Infinity_For_Reddit]
archive-dlurl = "https://archive.org/download/latest-infinity-patreon-for-revanced/apks/ml.docilealligator.infinityforreddit"
# Apkmirror & uptodown links are different version, needs the one from github this is why it uses archive link
# apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit/"
# uptodown-dlurl = "https://infinity-for-reddit.uptodown.com/android"
# apkmirror-dpi = "120-640dpi"
patcher-args = "-Oclient-id=_mmOs9BhDuXrQO2mLzRAcA"
included-patches = "'Unlock subscription' 'Spoof client'"
