parallel-jobs = 1
logging-to-file = true      # enables logging of every patch process to a seperate file
enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v2.190.0" # Temporal fix until original repo gets updated.

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "enable-debugging hide-cast-button microg-support old-quality-layout vanced-microg-support spoof-app-version"                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rv"

[Twitter]
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
module-prop-name = "x-rv"

[TikTok]
version = "30.8.4" # Temporal fix until original repo gets updated.
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
module-prop-name = "tiktok-rv"
